apiVersion: v1
data:
  tls.crt: $(cat kubernetes.pem | base64 | tr -d '\n')
  tls.key: $(cat kubernetes-key.pem | base64 | tr -d '\n')
kind: Secret
metadata:
  name: testsecret-tls
type: kubernetes.io/tls