provisionDataStore:
  cassandra: false
  elasticsearch: false

storage:
  # allowed values (cassandra, elasticsearch)
  type: elasticsearch
  elasticsearch:
    scheme: http
    host: elasticsearch.elasticsearch
    port: 9200
    user: elastic
    password: changeme
    nodesWanOnly: false

query:
  ingress:
    enabled: true
    # Used to create an Ingress record.
    hosts:
      - jaeger.scrollx.xyz
    annotations:
      kubernetes.io/ingress.class: traefik