version: '3'

services:
  php:
    container_name: php
    image: fitzix/php-pdo
    volumes:
      - ./ck:/var/www/html
    networks:
      - app_net
    build: ./php-pdo

  nginx:
    container_name: nginx
    image: nginx
    ports:
     - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ck:/usr/share/nginx/html
    networks:
      - app_net
    
  mysql:
    container_name: mysql
    image: mysql:5.6
    environment:
      LANG: C.UTF-8
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ck-mysql
      MYSQL_USER: ck
      MYSQL_PASSWORD: ck
      MYSQL_DATABASE: ck
    volumes:
      - ./mysql-data/:/var/lib/mysql
      - ./ck/db.sql:/docker-entrypoint-initdb.d/ck.sql
    networks:
      - app_net

networks:
  app_net: